"""empty message

Revision ID: 0093e15535e6
Revises: f1d360b72655
Create Date: 2021-10-18 11:02:44.148810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0093e15535e6'
down_revision = 'f1d360b72655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('cc', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('genre', sa.CHAR(), nullable=True))
    op.create_index(op.f('ix_users_cc'), 'users', ['cc'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cc'), table_name='users')
    op.drop_column('users', 'genre')
    op.drop_column('users', 'age')
    op.drop_column('users', 'cc')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
